# Xử lý lỗi

Lỗi là một thực tế trong vòng đời phần mềm, vì vậy Rust có một số tính năng xử lý các tình huống khi xảy ra sự cố. Trong nhiều trường hợp, Rust yêu cầu bạn phải biết khả năng xảy ra lỗi và thực hiện một số hành động xử lý trước khi mã của bạn được biên dịch. Yêu cầu này làm cho chương trình của bạn trở nên mạnh mẽ hơn bằng cách đảm bảo rằng bạn sẽ phát hiện ra lỗi và xử lý chúng một cách thích hợp trước khi triển khai đoạn mã của mình vào sản phẩm chính thức!

Rust nhóm các lỗi thành hai loại chính: lỗi *có thể khôi phục* và *không thể khôi phục*. Đối với lỗi có thể khôi phục, chẳng hạn như lỗi *file not found*, rất có thể chúng ta chỉ muốn báo cáo sự cố này cho người dùng và thử lại thao tác. Các lỗi không thể khôi phục luôn là biểu hiện của lỗi (bug) chương trình, ví dụ như cố gắng truy cập vào một vị trí nằm ngoài phạm vi của một mảng, và vì vậy chúng ta muốn dừng chương trình ngay lập tức.

Hầu hết các ngôn ngữ không phân biệt hai loại lỗi này và xử lý cả hai theo cùng một cách, sử dụng các cơ chế gọi là những ngoại lệ (exception). Rust không có những ngoại lệ kiểu này. Thay vào đó, nó có kiểu `Result<T,E>` cho các lỗi có thể khôi phục và macro `panic!` để dừng việc thực thi khi chương trình gặp lỗi không thể khôi phục. Chương này bao gồm: gọi `panic!` trước và sau đó nói tới việc trả về các giá trị `Result<T, E>`. Ngoài ra, chúng ta sẽ xem xét những cân nhắc khi quyết định nên cố gắng khôi phục lỗi xảy ra hay ngừng việc thực thi lại.
